import 'dart:math' as math;

import 'package:flutter/material.dart';

import '../../app/theme.dart';
import '../../core/game_definition.dart';
import '../../core/game_level_context.dart';
import '../../core/motion.dart';

/// Reference-original puzzle: a grid of rotatable path segments. Tap a tile
/// to spin it 90°; connect a fixed START tile to a fixed GOAL tile through a
/// chain of open sides. Loosely inspired by "rotate segments to build a
/// path" as a generic mechanic — original grid data, names and rendering.
final GameDefinition impossiblePathsDefinition = GameDefinition(
  id: 'impossible_paths',
  title: 'Path Rotate',
  tagline: 'Rotate tiles to connect the path',
  icon: Icons.timeline_rounded,
  tint: const GameTint(Color(0xFF34D399), Color(0xFF047857)),
  mode: GameMode.levels,
  levelCount: 15,
  builder: (context, ctx) => ImpossiblePathsScreen(ctx: ctx),
);

/// One of the four compass sides of a tile.
enum _Dir { n, e, s, w }

extension on _Dir {
  /// Rotating a tile 90° clockwise maps N->E->S->W->N.
  _Dir rotatedCw(int steps) => _Dir.values[(index + steps) % 4];

  _Dir get opposite => _Dir.values[(index + 2) % 4];
}

enum _Shape { straight, corner, tee, cross, empty, start, goal }

/// Open sides of each shape at rotation 0.
const Map<_Shape, Set<_Dir>> _baseOpenSides = {
  _Shape.straight: {_Dir.n, _Dir.s},
  _Shape.corner: {_Dir.n, _Dir.e},
  _Shape.tee: {_Dir.n, _Dir.e, _Dir.s},
  _Shape.cross: {_Dir.n, _Dir.e, _Dir.s, _Dir.w},
  _Shape.empty: {},
  _Shape.start: {_Dir.n},
  _Shape.goal: {_Dir.n},
};

Set<_Dir> _rotateSet(Set<_Dir> base, int steps) =>
    base.map((d) => d.rotatedCw(steps)).toSet();

bool _setEquals(Set<_Dir> a, Set<_Dir> b) =>
    a.length == b.length && a.every(b.contains);

/// Finds the rotation (0-3 steps of 90°) that turns a shape's base open
/// sides into exactly [required].
int _findRotation(_Shape shape, Set<_Dir> required) {
  final base = _baseOpenSides[shape]!;
  for (var k = 0; k < 4; k++) {
    if (_setEquals(_rotateSet(base, k), required)) return k;
  }
  throw StateError('No rotation of $shape matches $required');
}

_Dir _dirBetween((int, int) from, (int, int) to) {
  if (to.$1 < from.$1) return _Dir.n;
  if (to.$1 > from.$1) return _Dir.s;
  if (to.$2 < from.$2) return _Dir.w;
  return _Dir.e;
}

class _Cell {
  _Cell(this.shape, this.solvedRotation) : rotation = solvedRotation;

  final _Shape shape;
  final int solvedRotation;
  int rotation;

  bool get tappable =>
      shape == _Shape.straight || shape == _Shape.corner || shape == _Shape.tee;

  Set<_Dir> get openSides => _rotateSet(_baseOpenSides[shape]!, rotation);
}

/// Hand-authored puzzle: grid size + a path (start -> ... -> goal) of
/// grid-adjacent cells, generated by a deterministic row-snake so it is easy
/// to verify by hand that it never revisits a cell. A handful of interior
/// tiles are "upgraded" with 1 extra open side (tee) or 2 (cross) purely for
/// visual/tap complexity — since an extra open side that isn't matched by a
/// neighbour is simply inert, this can never break the guaranteed solved
/// path from start to goal.
class _LevelSpec {
  _LevelSpec({
    required this.rows,
    required this.cols,
    required this.path,
    required this.upgrades,
  });

  final int rows;
  final int cols;
  final List<(int, int)> path;

  /// pathIndex -> number of extra open sides to add (1 = tee, 2 = cross).
  final Map<int, int> upgrades;
}

/// Builds a snake path across [coveredRows] rows of [cols] columns, fully
/// covering every row except the last which only extends [lastRowSteps]
/// cells inward from the entry column. Remaining rows/cells in the grid are
/// left empty. Guaranteed distinct, in-bounds, grid-adjacent cells.
List<(int, int)> _snakePath(int coveredRows, int cols, int lastRowSteps) {
  final path = <(int, int)>[];
  for (var r = 0; r < coveredRows - 1; r++) {
    final leftToRight = r.isEven;
    for (var i = 0; i < cols; i++) {
      final c = leftToRight ? i : cols - 1 - i;
      path.add((r, c));
    }
  }
  final lastFullRow = coveredRows - 2;
  final entryCol = lastFullRow.isOdd ? 0 : cols - 1;
  final lastRow = coveredRows - 1;
  final lastRowLeftToRight = lastRow.isEven;
  final step = lastRowLeftToRight ? 1 : -1;
  var c = entryCol;
  path.add((lastRow, c));
  for (var i = 0; i < lastRowSteps; i++) {
    c += step;
    path.add((lastRow, c));
  }
  return path;
}

Map<int, int> _pickUpgrades(int pathLength, int count, int crossCount) {
  if (count <= 0) return {};
  final interiorMin = 1;
  final interiorMax = pathLength - 2;
  final span = interiorMax - interiorMin;
  final indices = <int>[];
  for (var i = 1; i <= count; i++) {
    var idx = interiorMin + (span * i / (count + 1)).round();
    while (indices.contains(idx) && idx < interiorMax) {
      idx++;
    }
    indices.add(idx.clamp(interiorMin, interiorMax));
  }
  final upgrades = <int, int>{};
  for (var i = 0; i < indices.length; i++) {
    final isCross = i >= indices.length - crossCount;
    upgrades[indices[i]] = isCross ? 2 : 1;
  }
  return upgrades;
}

_LevelSpec _makeLevel({
  required int rows,
  required int cols,
  required int coveredRows,
  required int lastRowSteps,
  required int upgradeCount,
  int crossCount = 0,
}) {
  final path = _snakePath(coveredRows, cols, lastRowSteps);
  final upgrades = _pickUpgrades(path.length, upgradeCount, crossCount);
  return _LevelSpec(rows: rows, cols: cols, path: path, upgrades: upgrades);
}

/// 15 hand-tuned puzzles: grid size, path coverage and rotation complexity
/// all grow with level. Each level's *solved* configuration is derived
/// directly from the adjacency of consecutive path cells (each cell opens
/// towards its path neighbours), which structurally guarantees a single
/// connected chain from start to goal at rotation-0-relative-to-solved for
/// every tile — hand-traced for levels 1 and 15 while authoring.
final List<_LevelSpec> _levels = [
  _makeLevel(rows: 4, cols: 4, coveredRows: 3, lastRowSteps: 0, upgradeCount: 0),
  _makeLevel(rows: 4, cols: 4, coveredRows: 3, lastRowSteps: 2, upgradeCount: 1),
  _makeLevel(rows: 4, cols: 4, coveredRows: 4, lastRowSteps: 0, upgradeCount: 1),
  _makeLevel(rows: 4, cols: 5, coveredRows: 3, lastRowSteps: 2, upgradeCount: 1),
  _makeLevel(rows: 4, cols: 5, coveredRows: 4, lastRowSteps: 1, upgradeCount: 2),
  _makeLevel(rows: 5, cols: 5, coveredRows: 4, lastRowSteps: 2, upgradeCount: 2),
  _makeLevel(rows: 5, cols: 5, coveredRows: 5, lastRowSteps: 1, upgradeCount: 2),
  _makeLevel(rows: 5, cols: 6, coveredRows: 4, lastRowSteps: 3, upgradeCount: 3),
  _makeLevel(rows: 5, cols: 6, coveredRows: 5, lastRowSteps: 2, upgradeCount: 3),
  _makeLevel(rows: 6, cols: 6, coveredRows: 5, lastRowSteps: 3, upgradeCount: 3, crossCount: 1),
  _makeLevel(rows: 6, cols: 6, coveredRows: 6, lastRowSteps: 1, upgradeCount: 4, crossCount: 1),
  _makeLevel(rows: 6, cols: 6, coveredRows: 6, lastRowSteps: 3, upgradeCount: 4, crossCount: 1),
  _makeLevel(rows: 6, cols: 6, coveredRows: 6, lastRowSteps: 5, upgradeCount: 5, crossCount: 1),
  _makeLevel(rows: 6, cols: 6, coveredRows: 6, lastRowSteps: 5, upgradeCount: 5, crossCount: 2),
  _makeLevel(rows: 6, cols: 6, coveredRows: 6, lastRowSteps: 5, upgradeCount: 6, crossCount: 2),
];

class ImpossiblePathsScreen extends StatefulWidget {
  const ImpossiblePathsScreen({super.key, required this.ctx});

  final GameLevelContext ctx;

  @override
  State<ImpossiblePathsScreen> createState() => _ImpossiblePathsScreenState();
}

class _ImpossiblePathsScreenState extends State<ImpossiblePathsScreen> {
  late _LevelSpec _spec;
  late List<List<_Cell>> _grid;
  late (int, int) _startPos;
  late (int, int) _goalPos;
  int _taps = 0;
  int _par = 1;
  bool _completed = false;
  Set<(int, int)> _connected = {};

  int get _level => widget.ctx.level;

  @override
  void initState() {
    super.initState();
    _spec = _levels[(_level - 1).clamp(0, _levels.length - 1)];
    _startPos = _spec.path.first;
    _goalPos = _spec.path.last;
    _grid = List.generate(
      _spec.rows,
      (_) => List.generate(_spec.cols, (_) => _Cell(_Shape.empty, 0)),
    );

    for (var i = 0; i < _spec.path.length; i++) {
      final pos = _spec.path[i];
      final dirs = <_Dir>{};
      if (i > 0) dirs.add(_dirBetween(pos, _spec.path[i - 1]));
      if (i < _spec.path.length - 1) dirs.add(_dirBetween(pos, _spec.path[i + 1]));

      _Shape shape;
      if (i == 0) {
        shape = _Shape.start;
      } else if (i == _spec.path.length - 1) {
        shape = _Shape.goal;
      } else {
        final extra = _spec.upgrades[i];
        if (extra != null) {
          final remaining = _Dir.values.where((d) => !dirs.contains(d)).toList();
          for (var k = 0; k < extra && k < remaining.length; k++) {
            dirs.add(remaining[k]);
          }
        }
        if (dirs.length >= 4) {
          shape = _Shape.cross;
        } else if (dirs.length == 3) {
          shape = _Shape.tee;
        } else {
          final opposite = (dirs.contains(_Dir.n) && dirs.contains(_Dir.s)) ||
              (dirs.contains(_Dir.e) && dirs.contains(_Dir.w));
          shape = opposite ? _Shape.straight : _Shape.corner;
        }
      }
      final solved = _findRotation(shape, dirs);
      _grid[pos.$1][pos.$2] = _Cell(shape, solved);
    }

    var par = 0;
    for (var r = 0; r < _spec.rows; r++) {
      for (var c = 0; c < _spec.cols; c++) {
        final idx = r * _spec.cols + c;
        final cell = _grid[r][c];
        if (cell.tappable) {
          final offset = (idx * 2 + _level) % 4;
          cell.rotation = (cell.solvedRotation + offset) % 4;
          if (cell.rotation != cell.solvedRotation) par++;
        }
      }
    }
    _par = math.max(1, par);
    _recomputeConnectivity();
    if (_connected.contains(_goalPos)) {
      // Deterministic scramble happened to already solve it; still reward.
      Future.microtask(() => _finish());
    }
  }

  bool _inBounds(int r, int c) => r >= 0 && r < _spec.rows && c >= 0 && c < _spec.cols;

  void _recomputeConnectivity() {
    final visited = <(int, int)>{_startPos};
    final queue = <(int, int)>[_startPos];
    while (queue.isNotEmpty) {
      final (r, c) = queue.removeLast();
      final openSides = _grid[r][c].openSides;
      for (final dir in openSides) {
        var nr = r;
        var nc = c;
        switch (dir) {
          case _Dir.n:
            nr -= 1;
          case _Dir.s:
            nr += 1;
          case _Dir.e:
            nc += 1;
          case _Dir.w:
            nc -= 1;
        }
        if (!_inBounds(nr, nc)) continue;
        if (visited.contains((nr, nc))) continue;
        if (_grid[nr][nc].openSides.contains(dir.opposite)) {
          visited.add((nr, nc));
          queue.add((nr, nc));
        }
      }
    }
    _connected = visited;
  }

  void _onTapCell(int r, int c) {
    if (_completed) return;
    final cell = _grid[r][c];
    if (!cell.tappable) return;
    setState(() {
      cell.rotation = (cell.rotation + 1) % 4;
      _taps++;
      _recomputeConnectivity();
    });
    if (_connected.contains(_goalPos)) {
      _finish();
    }
  }

  void _finish() {
    if (_completed) return;
    _completed = true;
    final stars = _taps <= _par ? 3 : (_taps <= _par * 2 ? 2 : 1);
    Future.microtask(() => widget.ctx.onComplete(stars: stars));
  }

  @override
  Widget build(BuildContext context) {
    final solved = _connected.contains(_goalPos);
    return Scaffold(
      appBar: AppBar(
        title: Text('Level $_level'),
        actions: [
          TextButton(
            onPressed: widget.ctx.onExit,
            child: const Text('Menu'),
          ),
        ],
      ),
      body: Column(
        children: [
          Padding(
            padding: const EdgeInsets.fromLTRB(20, 16, 20, 8),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text('Taps: $_taps', style: Theme.of(context).textTheme.titleMedium),
                Text(
                  solved ? 'Connected!' : 'Not connected',
                  style: TextStyle(
                    color: solved ? AppTheme.success : AppTheme.textSecondary,
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ],
            ),
          ),
          Expanded(
            child: Center(
              child: AspectRatio(
                aspectRatio: _spec.cols / _spec.rows,
                child: Padding(
                  padding: const EdgeInsets.all(20),
                  child: GridView.builder(
                    physics: const NeverScrollableScrollPhysics(),
                    itemCount: _spec.rows * _spec.cols,
                    gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                      crossAxisCount: _spec.cols,
                      mainAxisSpacing: 3,
                      crossAxisSpacing: 3,
                    ),
                    itemBuilder: (context, index) {
                      final r = index ~/ _spec.cols;
                      final c = index % _spec.cols;
                      final cell = _grid[r][c];
                      final isConnected = _connected.contains((r, c));
                      return GestureDetector(
                        onTap: cell.tappable ? () => _onTapCell(r, c) : null,
                        child: Container(
                          decoration: BoxDecoration(
                            color: AppTheme.surface,
                            borderRadius: BorderRadius.circular(8),
                          ),
                          child: AnimatedRotation(
                            turns: cell.rotation / 4,
                            duration: Motion.ms(180),
                            curve: Curves.easeOut,
                            child: CustomPaint(
                              painter: _TilePainter(
                                shape: cell.shape,
                                connected: isConnected,
                              ),
                            ),
                          ),
                        ),
                      );
                    },
                  ),
                ),
              ),
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(20),
            child: Text(
              'Tap a tile to rotate it 90°. Link open sides from the green '
              'start tile to the amber goal tile.',
              textAlign: TextAlign.center,
              style: TextStyle(color: AppTheme.textSecondary),
            ),
          ),
        ],
      ),
    );
  }
}

class _TilePainter extends CustomPainter {
  _TilePainter({required this.shape, required this.connected});

  final _Shape shape;
  final bool connected;

  @override
  void paint(Canvas canvas, Size size) {
    if (shape == _Shape.empty) return;

    final center = Offset(size.width / 2, size.height / 2);
    final lineColor = connected ? AppTheme.accent : const Color(0xFF3A4166);
    final paint = Paint()
      ..color = lineColor
      ..strokeWidth = size.shortestSide * 0.16
      ..strokeCap = StrokeCap.round;

    final sides = _baseOpenSides[shape]!;
    for (final dir in sides) {
      final edge = switch (dir) {
        _Dir.n => Offset(center.dx, 0),
        _Dir.s => Offset(center.dx, size.height),
        _Dir.e => Offset(size.width, center.dy),
        _Dir.w => Offset(0, center.dy),
      };
      canvas.drawLine(center, edge, paint);
    }

    if (shape == _Shape.start || shape == _Shape.goal) {
      final markerColor = shape == _Shape.start ? AppTheme.success : AppTheme.warning;
      canvas.drawCircle(
        center,
        size.shortestSide * 0.22,
        Paint()..color = markerColor,
      );
    } else {
      canvas.drawCircle(
        center,
        size.shortestSide * 0.09,
        Paint()..color = lineColor,
      );
    }
  }

  @override
  bool shouldRepaint(covariant _TilePainter oldDelegate) =>
      oldDelegate.shape != shape || oldDelegate.connected != connected;
}
