import 'dart:math';

import 'package:flutter/material.dart';

import '../../app/theme.dart';
import '../../core/game_definition.dart';
import '../../core/game_level_context.dart';
import '../../core/sound.dart';
import '../../core/widgets/game_actions.dart';

/// Reference implementation: an original dot-grid path puzzle. The player
/// traces a single line from a fixed start dot to a fixed end dot along
/// grid edges; the line divides the panel into regions and every colored
/// square must share its region with only same-colored squares. This is a
/// generic "path divides regions / match colors per region" mechanic (a
/// long-standing puzzle genre) implemented with original layouts, an
/// original name and no third-party art, symbols or branding.
final GameDefinition lineTraceDefinition = GameDefinition(
  id: 'line_trace',
  title: 'Region Trace',
  tagline: 'Trace a path that separates the colors',
  icon: Icons.route_rounded,
  tint: const GameTint(Color(0xFF38BDF8), Color(0xFF0369A1)),
  mode: GameMode.levels,
  levelCount: 15,
  helpText:
      'Drag from the start dot to the end dot along the grid lines. Your '
      'path carves the panel into regions — every region must contain only '
      'one color of square. Fewer failed attempts earns more stars.',
  builder: (context, ctx) => LineTraceScreen(ctx: ctx),
);

/// Colors used for the constraint squares. Kept distinct from the
/// success/danger flash colors used for feedback.
const List<Color> _squareColors = [
  Color(0xFF60A5FA), // blue
  Color(0xFFFB923C), // orange
  Color(0xFFC084FC), // purple (introduced on later, 3-color levels)
];

/// One hand-authored puzzle: a dot grid, fixed start/end dots, a map of
/// cell -> constraint color index, and a verified solution path (the exact
/// sequence of dots that solves the panel). The solution is never shown to
/// the player; it exists purely so every level is guaranteed solvable and
/// so the star rating has a reference to compare against.
class _LevelData {
  const _LevelData({
    required this.dotsX,
    required this.dotsY,
    required this.start,
    required this.end,
    required this.cellColors,
    required this.solution,
  });

  final int dotsX;
  final int dotsY;
  final Point<int> start;
  final Point<int> end;

  /// Cell coordinate (cx, cy) -> color index into [_squareColors].
  final Map<Point<int>, int> cellColors;

  /// A verified sequence of dots from [start] to [end] that solves the
  /// panel. Hand-traced and checked against the region algorithm below
  /// while authoring these levels.
  final List<Point<int>> solution;
}

/// A single diagonal staircase path from dot (0,0) to dot (n,n): it always
/// separates an n x n-cell panel into exactly two regions, cells with
/// (cy >= cx) on one side and cells with (cy < cx) on the other, no matter
/// how big `n` is — every (k,k) -> (k+1,k) -> (k+1,k+1) step draws exactly
/// the wall segment needed to keep that split, which is what
/// `_staircase3`/`_staircase4` below were hand-verifying for two fixed
/// sizes. Used to build faster-ramping, larger boards without needing a
/// fresh hand-trace per size.
List<Point<int>> _diagonalStaircase(int n) {
  final points = <Point<int>>[const Point(0, 0)];
  for (var k = 0; k < n; k++) {
    points.add(Point(k + 1, k));
    points.add(Point(k + 1, k + 1));
  }
  return points;
}

/// Level 1: a 3x3-cell panel (4x4 dots) split by the diagonal staircase.
/// Kept as its own named constant (rather than folded into
/// `_diagonalStaircase`) because `test/games/line_trace_logic_test.dart`
/// hand-copies this exact point list to drive level 1 — do not change it
/// without updating that test's `_level1Solution`.
const List<Point<int>> _staircase3 = [
  Point(0, 0),
  Point(1, 0),
  Point(1, 1),
  Point(2, 1),
  Point(2, 2),
  Point(3, 2),
  Point(3, 3),
];

/// Same diagonal-staircase idea on a 4x4-cell panel (5x5 dots).
const List<Point<int>> _staircase4 = [
  Point(0, 0),
  Point(1, 0),
  Point(1, 1),
  Point(2, 1),
  Point(2, 2),
  Point(3, 2),
  Point(3, 3),
  Point(4, 3),
  Point(4, 4),
];

/// Larger diagonal-staircase boards (5x5, 6x6, 7x7 cells) used to ramp
/// board size up quickly across the early levels, generated by
/// [_diagonalStaircase] rather than hand-authored per size.
final List<Point<int>> _staircase5 = _diagonalStaircase(5);
final List<Point<int>> _staircase6 = _diagonalStaircase(6);
final List<Point<int>> _staircase7 = _diagonalStaircase(7);

/// A 4x4-cell panel (5x5 dots). The path opens with a small loop that seals
/// off the top-left cell into its own single-cell region, then continues
/// as a staircase to the bottom-right corner. Hand-traced wall segments
/// confirm three regions: {(0,0)}, {(0,2),(0,3),(1,3)}, and the remaining
/// 12 cells.
const List<Point<int>> _pocket4 = [
  Point(0, 0),
  Point(1, 0),
  Point(1, 1),
  Point(0, 1),
  Point(0, 2),
  Point(1, 2),
  Point(1, 3),
  Point(2, 3),
  Point(2, 4),
  Point(3, 4),
  Point(4, 4),
];

/// A 5x5-cell panel (6x6 dots) using the same opening pocket followed by a
/// longer staircase. Hand-traced wall segments confirm three regions:
/// {(0,0)}, {(0,2),(0,3),(0,4),(1,3),(1,4),(2,4)}, and the remaining 18
/// cells.
const List<Point<int>> _pocket5 = [
  Point(0, 0),
  Point(1, 0),
  Point(1, 1),
  Point(0, 1),
  Point(0, 2),
  Point(1, 2),
  Point(1, 3),
  Point(2, 3),
  Point(2, 4),
  Point(3, 4),
  Point(3, 5),
  Point(4, 5),
  Point(5, 5),
];

final List<_LevelData> _levels = [
  // --- Level 1: 3x3 cells, 2 colors, diagonal split ----------------------
  // Kept byte-for-byte identical to the original level 1: its solution is
  // hand-copied into test/games/line_trace_logic_test.dart.
  _LevelData(
    dotsX: 4,
    dotsY: 4,
    start: const Point(0, 0),
    end: const Point(3, 3),
    cellColors: {
      Point(0, 1): 0,
      Point(1, 1): 0,
      Point(1, 0): 1,
      Point(2, 0): 1,
    },
    solution: _staircase3,
  ),

  // --- Level 2: 3x3 cells, 2 colors, more constraint squares -------------
  _LevelData(
    dotsX: 4,
    dotsY: 4,
    start: const Point(0, 0),
    end: const Point(3, 3),
    cellColors: {
      Point(0, 0): 0,
      Point(0, 1): 0,
      Point(1, 1): 0,
      Point(1, 0): 1,
      Point(2, 0): 1,
      Point(2, 1): 1,
    },
    solution: _staircase3,
  ),

  // --- Levels 3-4: 4x4 cells, 2 colors, diagonal split --------------------
  // Board size ramps up from level 3 already, instead of waiting until the
  // old level 7 — the panel and the number of constraint squares to track
  // both grow noticeably faster than before.
  _LevelData(
    dotsX: 5,
    dotsY: 5,
    start: const Point(0, 0),
    end: const Point(4, 4),
    cellColors: {
      Point(0, 0): 0,
      Point(1, 1): 0,
      Point(2, 2): 0,
      Point(1, 0): 1,
      Point(2, 0): 1,
      Point(3, 0): 1,
    },
    solution: _staircase4,
  ),
  _LevelData(
    dotsX: 5,
    dotsY: 5,
    start: const Point(0, 0),
    end: const Point(4, 4),
    cellColors: {
      Point(0, 1): 0,
      Point(0, 3): 0,
      Point(1, 3): 0,
      Point(3, 3): 0,
      Point(2, 1): 1,
      Point(3, 1): 1,
      Point(3, 2): 1,
    },
    solution: _staircase4,
  ),

  // --- Levels 5-7: 5x5, 6x6, then 7x7 cells, 2 colors ---------------------
  // The board keeps growing level over level instead of settling for three
  // levels at a time like the old ramp did — by level 7 the panel is
  // already nearly twice the area of the old "hardest" 2-color board.
  // cellColors satisfy the same (cy >= cx) vs (cy < cx) split
  // `_diagonalStaircase` guarantees for any size, so these are safe by
  // construction, not by a fresh hand-trace per level.
  _LevelData(
    dotsX: 6,
    dotsY: 6,
    start: const Point(0, 0),
    end: const Point(5, 5),
    cellColors: {
      Point(0, 2): 0,
      Point(1, 3): 0,
      Point(2, 4): 0,
      Point(0, 4): 0,
      Point(2, 0): 1,
      Point(3, 1): 1,
      Point(4, 2): 1,
      Point(1, 0): 1,
    },
    solution: _staircase5,
  ),
  _LevelData(
    dotsX: 7,
    dotsY: 7,
    start: const Point(0, 0),
    end: const Point(6, 6),
    cellColors: {
      Point(0, 3): 0,
      Point(1, 4): 0,
      Point(2, 5): 0,
      Point(0, 5): 0,
      Point(3, 0): 1,
      Point(4, 1): 1,
      Point(5, 2): 1,
      Point(1, 0): 1,
    },
    solution: _staircase6,
  ),
  _LevelData(
    dotsX: 8,
    dotsY: 8,
    start: const Point(0, 0),
    end: const Point(7, 7),
    cellColors: {
      Point(0, 3): 0,
      Point(1, 5): 0,
      Point(2, 6): 0,
      Point(0, 6): 0,
      Point(3, 4): 0,
      Point(3, 0): 1,
      Point(5, 1): 1,
      Point(6, 2): 1,
      Point(1, 0): 1,
      Point(4, 3): 1,
    },
    solution: _staircase7,
  ),

  // --- Levels 8-10: 4x4 cells, 3 colors, pocket split ---------------------
  // The third color (and the pocket mechanic that makes it possible — a
  // sealed single-cell region — unlocks two levels earlier than the old
  // ramp did.
  _LevelData(
    dotsX: 5,
    dotsY: 5,
    start: const Point(0, 0),
    end: const Point(4, 4),
    cellColors: {
      Point(0, 0): 2,
      Point(0, 2): 0,
      Point(0, 3): 0,
      Point(1, 0): 1,
      Point(3, 3): 1,
    },
    solution: _pocket4,
  ),
  _LevelData(
    dotsX: 5,
    dotsY: 5,
    start: const Point(0, 0),
    end: const Point(4, 4),
    cellColors: {
      Point(0, 0): 2,
      Point(0, 2): 0,
      Point(1, 3): 0,
      Point(2, 1): 1,
      Point(3, 2): 1,
    },
    solution: _pocket4,
  ),
  _LevelData(
    dotsX: 5,
    dotsY: 5,
    start: const Point(0, 0),
    end: const Point(4, 4),
    cellColors: {
      Point(0, 0): 2,
      Point(0, 2): 0,
      Point(0, 3): 0,
      Point(1, 3): 0,
      Point(1, 0): 1,
      Point(2, 0): 1,
      Point(0, 1): 1,
      Point(2, 2): 1,
      Point(3, 3): 1,
    },
    solution: _pocket4,
  ),

  // --- Levels 11-13: 5x5 cells, 3 colors, pocket split --------------------
  _LevelData(
    dotsX: 6,
    dotsY: 6,
    start: const Point(0, 0),
    end: const Point(5, 5),
    cellColors: {
      Point(0, 0): 2,
      Point(0, 3): 0,
      Point(1, 4): 0,
      Point(2, 1): 1,
      Point(4, 3): 1,
    },
    solution: _pocket5,
  ),
  _LevelData(
    dotsX: 6,
    dotsY: 6,
    start: const Point(0, 0),
    end: const Point(5, 5),
    cellColors: {
      Point(0, 0): 2,
      Point(0, 2): 0,
      Point(0, 4): 0,
      Point(1, 3): 0,
      Point(3, 0): 1,
      Point(4, 1): 1,
      Point(4, 4): 1,
    },
    solution: _pocket5,
  ),
  _LevelData(
    dotsX: 6,
    dotsY: 6,
    start: const Point(0, 0),
    end: const Point(5, 5),
    cellColors: {
      Point(0, 0): 2,
      Point(0, 3): 0,
      Point(1, 3): 0,
      Point(2, 4): 0,
      Point(1, 0): 1,
      Point(2, 0): 1,
      Point(3, 3): 1,
      Point(4, 2): 1,
    },
    solution: _pocket5,
  ),

  // --- Levels 14-15: 5x5 cells, 3 colors, pocket split, maximum density ---
  // The last two levels reuse the same verified pocket-5 solution/regions
  // but pack in far more constraint squares (every safe cell in the two
  // smaller regions, plus most of the big region) than any earlier level —
  // a genuine late-game difficulty spike from visual density and having to
  // track many more constraints at once, on top of the already-largest
  // 2-color-tier board size.
  _LevelData(
    dotsX: 6,
    dotsY: 6,
    start: const Point(0, 0),
    end: const Point(5, 5),
    cellColors: {
      Point(0, 0): 2,
      Point(0, 2): 0,
      Point(0, 3): 0,
      Point(0, 4): 0,
      Point(1, 3): 0,
      Point(1, 4): 0,
      Point(2, 4): 0,
      Point(0, 1): 1,
      Point(1, 0): 1,
      Point(1, 1): 1,
      Point(2, 2): 1,
      Point(3, 0): 1,
      Point(3, 3): 1,
      Point(4, 1): 1,
      Point(4, 4): 1,
    },
    solution: _pocket5,
  ),
  _LevelData(
    dotsX: 6,
    dotsY: 6,
    start: const Point(0, 0),
    end: const Point(5, 5),
    cellColors: {
      Point(0, 0): 2,
      Point(0, 2): 0,
      Point(0, 3): 0,
      Point(0, 4): 0,
      Point(1, 3): 0,
      Point(1, 4): 0,
      Point(2, 4): 0,
      Point(0, 1): 1,
      Point(1, 0): 1,
      Point(1, 1): 1,
      Point(1, 2): 1,
      Point(2, 0): 1,
      Point(2, 2): 1,
      Point(2, 3): 1,
      Point(3, 1): 1,
      Point(3, 3): 1,
      Point(3, 4): 1,
      Point(4, 0): 1,
      Point(4, 3): 1,
    },
    solution: _pocket5,
  ),
];

class LineTraceScreen extends StatefulWidget {
  const LineTraceScreen({super.key, required this.ctx});

  final GameLevelContext ctx;

  @override
  State<LineTraceScreen> createState() => _LineTraceScreenState();
}

class _LineTraceScreenState extends State<LineTraceScreen> {
  late _LevelData _data;
  late List<Point<int>> _path;
  Set<Point<int>> _flashCells = {};
  Color? _flashColor;
  int _failedAttempts = 0;
  bool _locked = false;

  @override
  void initState() {
    super.initState();
    final index = (widget.ctx.level - 1).clamp(0, _levels.length - 1);
    _data = _levels[index];
    _path = [_data.start];
  }

  bool get _isComplete => _path.length > 1 && _path.last == _data.end;

  int _starsForAttempts() {
    if (_failedAttempts <= 0) return 3;
    if (_failedAttempts <= 2) return 2;
    return 1;
  }

  void _handleTouch(Offset local, double cellSize) {
    if (_locked) return;
    final gx = (local.dx / cellSize).round().clamp(0, _data.dotsX - 1);
    final gy = (local.dy / cellSize).round().clamp(0, _data.dotsY - 1);
    final dot = Point(gx, gy);
    if (dot == _path.last) return;

    // Drag-back undo: returning to the second-to-last dot pops the last
    // segment, giving a forgiving undo-by-dragback feel.
    if (_path.length >= 2 && dot == _path[_path.length - 2]) {
      setState(() => _path.removeLast());
      return;
    }

    final last = _path.last;
    final isAdjacent = (dot.x - last.x).abs() + (dot.y - last.y).abs() == 1;
    if (!isAdjacent || _path.contains(dot)) return;

    setState(() => _path.add(dot));
    if (_isComplete) _checkSolution();
  }

  /// Finalizes a drag that ended (lift or system cancel) without reaching
  /// [_LevelData.end]: since tracing is meant to be one continuous stroke
  /// from start to end, an incomplete release abandons the partial trace
  /// (counted as a failed attempt), matching [_clear]'s bookkeeping. A
  /// completed path is already handled by [_checkSolution] before the pan
  /// ever ends, so this is a no-op in that case.
  void _handlePanEnd() {
    if (_locked) return;
    if (_path.length <= 1) return;
    if (_isComplete) return;
    setState(() {
      _failedAttempts++;
      _path = [_data.start];
      _flashCells = {};
      _flashColor = null;
    });
  }

  /// Reveals the next dot beyond wherever the player's current path
  /// currently ends, taken from the verified reference [_LevelData.solution].
  void _showHint() {
    if (_locked || _isComplete) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('This level looks complete!')),
      );
      return;
    }
    final lastDot = _path.last;
    final idx = _data.solution.indexOf(lastDot);
    if (idx == -1 || idx >= _data.solution.length - 1) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text(
            'Your path has drifted from the reference route — try Clear '
            'and retrace from the start dot for a hint.',
          ),
        ),
      );
      return;
    }
    final next = _data.solution[idx + 1];
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text('Trace toward dot (${next.x}, ${next.y}) next.')),
    );
  }

  void _clear() {
    if (_locked) return;
    setState(() {
      if (_path.length > 1) _failedAttempts++;
      _path = [_data.start];
      _flashCells = {};
      _flashColor = null;
    });
  }

  /// Restarts the current level's attempt from the start dot without
  /// leaving the screen or opening a dialog — the same bookkeeping as the
  /// existing "Clear" button ([_clear]), just reachable from the AppBar
  /// action added for every game, with tap feedback.
  void _restartLevel() {
    Sfx.tap();
    _clear();
  }

  /// Flood-fills the panel's cells, treating drawn path segments as walls
  /// between adjacent cells, and returns the resulting connected regions.
  List<Set<Point<int>>> _computeRegions() {
    final gw = _data.dotsX - 1;
    final gh = _data.dotsY - 1;
    final vWalls = <Point<int>>{}; // (x, y) => vertical segment (x,y)-(x,y+1)
    final hWalls = <Point<int>>{}; // (x, y) => horizontal segment (x,y)-(x+1,y)
    for (var i = 0; i < _path.length - 1; i++) {
      final a = _path[i];
      final b = _path[i + 1];
      if (a.x == b.x) {
        vWalls.add(Point(a.x, min(a.y, b.y)));
      } else {
        hWalls.add(Point(min(a.x, b.x), a.y));
      }
    }

    bool blockedRight(int cx, int cy) => vWalls.contains(Point(cx + 1, cy));
    bool blockedDown(int cx, int cy) => hWalls.contains(Point(cx, cy + 1));

    final visited = <Point<int>>{};
    final regions = <Set<Point<int>>>[];
    for (var cy = 0; cy < gh; cy++) {
      for (var cx = 0; cx < gw; cx++) {
        final start = Point(cx, cy);
        if (visited.contains(start)) continue;
        final region = <Point<int>>{};
        final queue = <Point<int>>[start];
        visited.add(start);
        while (queue.isNotEmpty) {
          final cell = queue.removeLast();
          region.add(cell);
          final x = cell.x;
          final y = cell.y;
          final neighbors = <Point<int>>[
            if (x + 1 < gw && !blockedRight(x, y)) Point(x + 1, y),
            if (x - 1 >= 0 && !blockedRight(x - 1, y)) Point(x - 1, y),
            if (y + 1 < gh && !blockedDown(x, y)) Point(x, y + 1),
            if (y - 1 >= 0 && !blockedDown(x, y - 1)) Point(x, y - 1),
          ];
          for (final n in neighbors) {
            if (visited.add(n)) queue.add(n);
          }
        }
        regions.add(region);
      }
    }
    return regions;
  }

  void _checkSolution() {
    final regions = _computeRegions();
    Set<Point<int>>? offending;
    for (final region in regions) {
      final colorsInRegion = <int>{};
      for (final cell in region) {
        final c = _data.cellColors[cell];
        if (c != null) colorsInRegion.add(c);
      }
      if (colorsInRegion.length > 1) {
        offending = region;
        break;
      }
    }

    if (offending == null) {
      setState(() {
        _locked = true;
        _flashCells = _data.cellColors.keys.toSet();
        _flashColor = AppTheme.success;
      });
      Future.delayed(const Duration(milliseconds: 600), () {
        if (!mounted) return;
        widget.ctx.onComplete(stars: _starsForAttempts());
      });
    } else {
      setState(() {
        _locked = true;
        _flashCells = offending!;
        _flashColor = AppTheme.danger;
        _failedAttempts++;
      });
      Future.delayed(const Duration(milliseconds: 600), () {
        if (!mounted) return;
        setState(() {
          _path = [_data.start];
          _flashCells = {};
          _flashColor = null;
          _locked = false;
        });
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Level ${widget.ctx.level}'),
        actions: [
          ...gameActions(
            context: context,
            def: lineTraceDefinition,
            ctx: widget.ctx,
            onHint: _showHint,
            onRestart: _restartLevel,
          ),
          IconButton(
            icon: const Icon(Icons.flag_outlined),
            tooltip: 'Give up',
            onPressed: widget.ctx.onExit,
          ),
        ],
      ),
      body: Column(
        children: [
          Padding(
            padding: const EdgeInsets.fromLTRB(20, 16, 20, 8),
            child: Text(
              'Attempts: $_failedAttempts',
              style: Theme.of(context).textTheme.titleLarge,
            ),
          ),
          Expanded(
            child: Center(
              child: AspectRatio(
                aspectRatio: 1,
                child: LayoutBuilder(
                  builder: (context, constraints) {
                    const boardPadding = 24.0;
                    final outerSize = constraints.maxWidth;
                    final size = outerSize - boardPadding * 2;
                    final cellSize = size / (_data.dotsX - 1);
                    // GestureDetector wraps the Padding (rather than the
                    // reverse) and is `opaque`, so its hit-test area is the
                    // full outer square, including the padding ring — a
                    // drag starting there no longer misses the board
                    // entirely. `localPosition` is relative to that outer
                    // edge, so it's shifted back by `boardPadding` before
                    // being converted to dot coordinates.
                    Offset toCanvas(Offset local) =>
                        local - const Offset(boardPadding, boardPadding);
                    return GestureDetector(
                      behavior: HitTestBehavior.opaque,
                      onPanStart: (d) =>
                          _handleTouch(toCanvas(d.localPosition), cellSize),
                      onPanUpdate: (d) =>
                          _handleTouch(toCanvas(d.localPosition), cellSize),
                      onPanEnd: (_) => _handlePanEnd(),
                      onPanCancel: _handlePanEnd,
                      child: Padding(
                        padding: const EdgeInsets.all(boardPadding),
                        child: CustomPaint(
                          size: Size(size, size),
                          painter: _LineTracePainter(
                            data: _data,
                            path: _path,
                            flashCells: _flashCells,
                            flashColor: _flashColor,
                          ),
                        ),
                      ),
                    );
                  },
                ),
              ),
            ),
          ),
          Padding(
            padding: const EdgeInsets.fromLTRB(20, 8, 20, 4),
            child: ElevatedButton(
              onPressed: _clear,
              child: const Text('Clear'),
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(20),
            child: Text(
              'Drag from start to end. Every region your path carves out must '
              'contain only one color of square.',
              textAlign: TextAlign.center,
              style: TextStyle(color: AppTheme.textSecondary),
            ),
          ),
        ],
      ),
    );
  }
}

class _LineTracePainter extends CustomPainter {
  _LineTracePainter({
    required this.data,
    required this.path,
    required this.flashCells,
    required this.flashColor,
  });

  final _LevelData data;
  final List<Point<int>> path;
  final Set<Point<int>> flashCells;
  final Color? flashColor;

  @override
  void paint(Canvas canvas, Size size) {
    final gw = data.dotsX - 1;
    final gh = data.dotsY - 1;
    final cellSize = size.width / gw;

    final boardRect = Rect.fromLTWH(0, 0, size.width, size.height);
    canvas.drawRRect(
      RRect.fromRectAndRadius(boardRect, const Radius.circular(16)),
      Paint()..color = AppTheme.surfaceHigh,
    );

    // Faint grid lines to show cell boundaries.
    final gridPaint = Paint()
      ..color = AppTheme.accentSoft.withValues(alpha: 0.25)
      ..strokeWidth = 1;
    for (var i = 0; i <= gw; i++) {
      final x = i * cellSize;
      canvas.drawLine(Offset(x, 0), Offset(x, size.height), gridPaint);
    }
    for (var j = 0; j <= gh; j++) {
      final y = j * cellSize;
      canvas.drawLine(Offset(0, y), Offset(size.width, y), gridPaint);
    }

    // Flash overlay for the regions being highlighted (success/error).
    if (flashColor != null) {
      final flashPaint = Paint()..color = flashColor!.withValues(alpha: 0.35);
      for (final cell in flashCells) {
        final rect = Rect.fromLTWH(
          cell.x * cellSize,
          cell.y * cellSize,
          cellSize,
          cellSize,
        );
        canvas.drawRect(rect, flashPaint);
      }
    }

    // Colored constraint squares.
    for (final entry in data.cellColors.entries) {
      final cell = entry.key;
      final color = _squareColors[entry.value % _squareColors.length];
      final margin = cellSize * 0.28;
      final rect = Rect.fromLTWH(
        cell.x * cellSize + margin,
        cell.y * cellSize + margin,
        cellSize - margin * 2,
        cellSize - margin * 2,
      );
      canvas.drawRRect(
        RRect.fromRectAndRadius(rect, const Radius.circular(6)),
        Paint()..color = color,
      );
    }

    // Dots.
    final dotPaint = Paint()..color = AppTheme.textSecondary;
    for (var y = 0; y < data.dotsY; y++) {
      for (var x = 0; x < data.dotsX; x++) {
        canvas.drawCircle(Offset(x * cellSize, y * cellSize), 4, dotPaint);
      }
    }

    // Start/end markers.
    canvas.drawCircle(
      Offset(data.start.x * cellSize, data.start.y * cellSize),
      9,
      Paint()..color = AppTheme.accent,
    );
    canvas.drawCircle(
      Offset(data.end.x * cellSize, data.end.y * cellSize),
      9,
      Paint()..color = AppTheme.warning,
    );

    // The traced path.
    if (path.length > 1) {
      final pathPaint = Paint()
        ..color = AppTheme.accent
        ..strokeWidth = 8
        ..strokeCap = StrokeCap.round
        ..strokeJoin = StrokeJoin.round
        ..style = PaintingStyle.stroke;
      final uiPath = Path()
        ..moveTo(path.first.x * cellSize, path.first.y * cellSize);
      for (final dot in path.skip(1)) {
        uiPath.lineTo(dot.x * cellSize, dot.y * cellSize);
      }
      canvas.drawPath(uiPath, pathPaint);
    }
  }

  @override
  bool shouldRepaint(covariant _LineTracePainter oldDelegate) {
    return oldDelegate.path != path ||
        oldDelegate.flashCells != flashCells ||
        oldDelegate.flashColor != flashColor;
  }
}
